services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "2009scape_app"
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - "2009scape_app:/app/2009scape"  # Changed to match WORKDIR
    environment:
      - TZ=America/New_York
    ports:
      - "43595:43595"
    networks:
      - 2009scape_network
    healthcheck:
      test: ["CMD", "netstat", "-an", "|", "grep", "43595"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: mysql:8.0
    container_name: "2009scape_db"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "2009scape_db:/var/lib/mysql"
    environment:
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=567326
      - MYSQL_ROOT_USER=jordan
      - MYSQL_DATABASE=2009scape
    networks:
      - 2009scape_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ujordan", "-p567326"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "2009scape_client"
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "5900:5900"
    volumes:
      - "2009scape_client:/app"
    environment:
      - TZ=America/New_York
      - SERVER_HOST=app
      - SERVER_PORT=43595
      - DISPLAY=:1
    depends_on:
      - app
    networks:
      - 2009scape_network

  nginx:
    image: nginx:1.25-alpine
    container_name: "2009scape_nginx"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./config/html:/usr/share/nginx/html:ro
    environment:
      - TZ=America/New_York
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - app
      - client
      - database
    networks:
      - 2009scape_network

volumes:
  2009scape_app:
  2009scape_db:
  2009scape_client:

networks:
  2009scape_network:
    driver: bridge